// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SE1811.DAO;

#nullable disable

namespace SE1811.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20250521055710_v0")]
    partial class v0
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SE1811.model.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<string>("DescriptionProduct")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameProduct")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            DescriptionProduct = "Classic acoustic guitar",
                            NameProduct = "Guitar"
                        },
                        new
                        {
                            ProductID = 2,
                            DescriptionProduct = "88-key digital piano",
                            NameProduct = "Piano"
                        },
                        new
                        {
                            ProductID = 3,
                            DescriptionProduct = "Standard 5-piece drum set",
                            NameProduct = "Drum Set"
                        },
                        new
                        {
                            ProductID = 4,
                            DescriptionProduct = "Full size violin",
                            NameProduct = "Violin"
                        },
                        new
                        {
                            ProductID = 5,
                            DescriptionProduct = "Silver concert flute",
                            NameProduct = "Flute"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
