// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SE1811.DAO;

#nullable disable

namespace SE1811.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20250529150218_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SE1811.model.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Instruments",
                            Description = "Musical instruments category"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Electronics",
                            Description = "Electronic devices category"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Books",
                            Description = "All kinds of books"
                        });
                });

            modelBuilder.Entity("SE1811.model.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionProduct")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameProduct")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            CategoryID = 1,
                            DescriptionProduct = "Classic acoustic guitar",
                            NameProduct = "Guitar",
                            Price = 0
                        },
                        new
                        {
                            ProductID = 2,
                            CategoryID = 1,
                            DescriptionProduct = "88-key digital piano",
                            NameProduct = "Piano",
                            Price = 0
                        },
                        new
                        {
                            ProductID = 3,
                            CategoryID = 1,
                            DescriptionProduct = "Standard 5-piece drum set",
                            NameProduct = "Drum Set",
                            Price = 0
                        },
                        new
                        {
                            ProductID = 4,
                            CategoryID = 1,
                            DescriptionProduct = "Full size violin",
                            NameProduct = "Violin",
                            Price = 0
                        },
                        new
                        {
                            ProductID = 5,
                            CategoryID = 1,
                            DescriptionProduct = "Silver concert flute",
                            NameProduct = "Flute",
                            Price = 0
                        },
                        new
                        {
                            ProductID = 6,
                            CategoryID = 2,
                            DescriptionProduct = "DSLR professional",
                            NameProduct = "Canon Camera",
                            Price = 0
                        },
                        new
                        {
                            ProductID = 7,
                            CategoryID = 2,
                            DescriptionProduct = "Mobile phone",
                            NameProduct = "Samsung Galaxy",
                            Price = 0
                        },
                        new
                        {
                            ProductID = 8,
                            CategoryID = 2,
                            DescriptionProduct = "Apple laptop",
                            NameProduct = "MacBook Air",
                            Price = 0
                        },
                        new
                        {
                            ProductID = 9,
                            CategoryID = 2,
                            DescriptionProduct = "Wireless",
                            NameProduct = "Logitech Mouse",
                            Price = 0
                        },
                        new
                        {
                            ProductID = 10,
                            CategoryID = 2,
                            DescriptionProduct = "24-inch screen",
                            NameProduct = "HP Monitor",
                            Price = 0
                        },
                        new
                        {
                            ProductID = 11,
                            CategoryID = 3,
                            DescriptionProduct = "Beginner to Advanced",
                            NameProduct = "C# Programming",
                            Price = 0
                        },
                        new
                        {
                            ProductID = 12,
                            CategoryID = 3,
                            DescriptionProduct = "A Handbook of Agile Software Craftsmanship",
                            NameProduct = "Clean Code",
                            Price = 0
                        });
                });

            modelBuilder.Entity("SE1811.model.Product", b =>
                {
                    b.HasOne("SE1811.model.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SE1811.model.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
